[2022-09-17T13:55:30.290+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T13:55:28.052419+00:00 [queued]>
[2022-09-17T13:55:30.305+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T13:55:28.052419+00:00 [queued]>
[2022-09-17T13:55:30.306+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-17T13:55:30.307+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-17T13:55:30.308+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-17T13:55:30.328+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): download_Dataset_task> on 2022-09-17 13:55:28.052419+00:00
[2022-09-17T13:55:30.339+0000] {standard_task_runner.py:52} INFO - Started process 97 to run task
[2022-09-17T13:55:30.350+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_Dataset_task', 'manual__2022-09-17T13:55:28.052419+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpj90uvxz3', '--error-file', '/tmp/tmpl4srr8zp']
[2022-09-17T13:55:30.356+0000] {standard_task_runner.py:80} INFO - Job 66: Subtask download_Dataset_task
[2022-09-17T13:55:30.499+0000] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T13:55:28.052419+00:00 [running]> on host 9071d3605dea
[2022-09-17T13:55:30.617+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_Dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T13:55:28.052419+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-17T13:55:28.052419+00:00
[2022-09-17T13:55:30.622+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-17T13:55:30.623+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'gdown --id $1PVxj7DIHZb3RIvuKTrhl873rBUcaonwd -O yellow_tripdata_2021-01.csv']
[2022-09-17T13:55:30.645+0000] {subprocess.py:85} INFO - Output:
[2022-09-17T13:55:31.462+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
[2022-09-17T13:55:31.464+0000] {subprocess.py:92} INFO -   category=FutureWarning,
[2022-09-17T13:55:31.465+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-09-17T13:55:31.466+0000] {subprocess.py:92} INFO -   File "/home/***/.local/bin/gdown", line 8, in <module>
[2022-09-17T13:55:31.467+0000] {subprocess.py:92} INFO -     sys.exit(main())
[2022-09-17T13:55:31.468+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/gdown/cli.py", line 166, in main
[2022-09-17T13:55:31.469+0000] {subprocess.py:92} INFO -     resume=args.continue_,
[2022-09-17T13:55:31.469+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/gdown/download.py", line 120, in download
[2022-09-17T13:55:31.470+0000] {subprocess.py:92} INFO -     os.makedirs(cache_dir)
[2022-09-17T13:55:31.471+0000] {subprocess.py:92} INFO -   File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
[2022-09-17T13:55:31.472+0000] {subprocess.py:92} INFO -     mkdir(name, mode)
[2022-09-17T13:55:31.472+0000] {subprocess.py:92} INFO - PermissionError: [Errno 13] Permission denied: '/home/***/.cache/gdown'
[2022-09-17T13:55:31.493+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2022-09-17T13:55:31.511+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-09-17T13:55:31.517+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_Dataset_task, execution_date=20220917T135528, start_date=20220917T135530, end_date=20220917T135531
[2022-09-17T13:55:31.534+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 66 for task download_Dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 97)
[2022-09-17T13:55:31.580+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-17T13:55:31.635+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
